# Generated by Django 3.2 on 2024-12-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='feedback_customer',
        ),
    ]
